### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [nolit1/RunBroRun#1]
0. Следует написать модульные тесты.
1. При проходе мимо шипов игрок не проигрывает и очки начисляются. Так и задумано?
2. Если вы отказались от сборки под Андроид и Веб, то сделайте так, чтобы версии для этих платформ не собирались вообще (удалите лишний код и поправьте скрипты сборки). А то для сборки всего этого добра требуется Android SDK, а на выходе приложения под Андроид нет.
3. В коде встречаются "магические" числа. Следует вынести их в константы.
4. В классе `GameRenderer` имеются изменяемые статические поля. Это плохой стиль, нужно это исправить.
5. (по README) Вместо текстур и красивостей лучше поработать над механикой игры, потому как игра получилась, как мне кажется, сильно проще, чем задумывалась. Текстуры/анимации - дело десятое. (Этот пункт сам по себе имеет меньший приоритет, чем предудущие, в первую очередь займитесь теми, что выше)

**Comment by nolit1** [comment]
При проходе мимо шипов игрок не проигрывает и очки начисляются. Так и задумано? - Нет, так не задумано, работаю над этим.
Хорошо, исправлю

**Comment by gagarski** [comment]
#0, #4 всё ещё актуально

Не хватает каких-то текстур в репозитории, игра падает при запуске:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: data/texture3.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:147)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at com.runbrorun.Helpers.AssetLoader.load(AssetLoader.java:35)
	at com.runbrorun.Bro.create(Bro.java:13)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: data/texture3.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
	... 7 more
```

**Comment by nolit1** [comment]
Да, у меня тоже вылезло сейчас. Там в "edit configuration" нужно указать путь в "workong directory" ..\Bro\core\assets . Сейчас перезалью на гитхаб, может и у вас исправится

**Comment by gagarski** [comment]
Это я делал, но не помогло, там действительно не было нужного файла.

**Comment by gagarski** [comment]
Это я делал, но не помогло, там действительно не было нужного файла.

2017-05-30 18:13 GMT+03:00 nolit1 <notifications@github.com>:

**Comment by nolit1** [comment]
всё, отправил, да

**Comment by nolit1** [comment]
я добавил файл. Странно что до этого не залился...

**Comment by nolit1** [comment]
теперь должно работать

**Comment by nolit1** [comment]
А как тест должен выглядеть? Стандартный вопрос, но всё же я не очень понимаю. Например, перемещается ли у меня персонаж при нажатии кнопки?
